#!/bin/bash

source ~/.bashrc

# Where's my Python
source /datascope/slurm/miniconda3/bin/activate ae-tf
export PYTHONPATH=.:../pysynphot:../SciScript-Python/py3

# Where's my PFS 
export AE_ROOT=/home/swei20/AE
export AE_DATA=/scratch/ceph/swei20/data/ae
export AE_TEST=/scratch/ceph/swei20/data/ae/test


# Work around issues with saving weights when running on multiple threads
export HDF5_USE_FILE_LOCKING=FALSE

# Disable tensorflow deprecation warnings
export TF_CPP_MIN_LOG_LEVEL=2

# Enable more cores for numexpr
export NUMEXPR_MAX_THREADS=32


cd $AE_ROOT

echo "Encode! Encode! "
echo "Data directory is $AE_DATA"